version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - psql
 
  psql:
    image: postgres:11.9
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=user
      - POSTGRES_DB=database